appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: UovIFsEoxBbXbWzCP22AcDSSs/NTVCB0Yt2Ou450fkLoZZDmu9thXz9Nh+lkEKZIxQ4giQtV0EnToZlSLyaoKITbCUYxrC/NtOe2pCfnFYcVtIWE6kKrBPAnV2WokVfrhZI3ACVFOoNp/UW9X0Rhp4t8wseMAFc9mHvEqGykspkTAiLKys1YQm2Ri1wsEkW/gpL5Hx747TIfrKCoDL6SmGPFB9eZfiBwW4lulXdDplmLN+eQ9A7QRu2fGw4B3Xv/+wedQH6lF7eRYAyO+LskjP3Gyo8r8etajzD1LI7RS0OaAqDCQWLbEeS5NkIt6WiAweAHpSSJLe+KCIp69bXX8fN9ZvZV4jdLV3ugawZI8k1h6BfaNdycZ+ASRIgrhkLYp4VxOznUuvXuue+MG3xw2HiFN0l36lMOab/hvAEhqNv+lsb7kLxhLiyTBlV4g8T0HTnrCEW0s+lIddgUJpxRVJUQOflTUjsiOxxTulNERmXwec+2XC57wiOnQV5Vwf+5chKumVuthNXXbRT9gWuLCok7I71cQHwB8xhQG0HOI2LUxli11EfcxikfKQKO3cEDxnE5A4d4+exg4tvzZWRAji+IZO/ptplc9FsdlWOtbRSLEqrInUf17GJufHUOr9wHeoVTvQwwowdsZl5LFOZ+jCOZYze7Sg3Af87mmWuKlrQ=}
bot:
  automerge: true
